### ISSUE TITLE
Would you add MD5?  or do you have MD5 for C++ someplace else? 

### ISSUE THREAD

**Issue by vhvb1989** [sergey-shandar/sha2#15]

**Comment by sergey-shandar** [comment]
No, I don't have MD5 and plans to implement it.

**Comment by vhvb1989** [comment]
Sergey does not want to implement MD5

**Comment by sergey-shandar** [comment]
Will [this one](https://github.com/stbrumme/hash-library) work for you? Also, I believe, MD5 is quite simple so I'm accepting PRs :-)
